### ISSUE TITLE
Mountain Giant lvl 20 Q replacement doesn't do splash damage

### ISSUE THREAD

**Issue by peitschie** [EarthSalamander42/x_hero_siege#1]
As titled. The Q stops doing splash damage once the hero hits level 20, even though the character carries the tree still, and the description says the skill should splash.

(P.s., just thought I'd raise the issue here directly so it doesn't get lost in the endless list of comments on the steam site... feel free to complain if you'd prefer I did these on the Steam page.)

**Comment by peitschie** [comment]
I'm a bit confused about the Hero name, sorry! Seems its "Stone Giant" in the game 😊

**Comment by EarthSalamander42** [comment]
Thank you for reporting! Yeah tbh, it's way better here :) I'll take a look at it today

**Comment by peitschie** [comment]
You might have already fixed this one. I reported it against 3.42... but noticed you made some changes to this in 3.43 already. It's possible this is already done 😄

**Comment by EarthSalamander42** [comment]
Fixed again in 3.43b :)
