### ISSUE TITLE
Farm event pulls player out of special arena without pausing arena

### ISSUE THREAD

**Issue by peitschie** [EarthSalamander42/x_hero_siege#11]
I had a situation where I just hit the second special arena as the farming event started. This resulted in me appearing in the special arena for a few moments, before being teleported back out to the farming event. The special arena then times out causing me to lose it.

After the farming event completed, my character stayed in the farm pit for 1-20s longer before finally being teleported back to the main castle for some reason.

**Comment by peitschie** [comment]
Oh, this was found in 3.44f

**Comment by EarthSalamander42** [comment]
Hmm, so the farm event began, and while in, special arena?

**Comment by peitschie** [comment]
Yep! Sequence of events was:

1. Entered special arena (approx 10s before farm event begins)
2. Got teleported farm event when it starts
3. Farm event ran as per normal. During the farm event, all players got notified that the special arena was lost
4. Upon completion of the farm event, the other player returned to the keep immediatelym but I was stuck in the now empty farm event for another 10-20s before being teleported back to the keep.

The game continued on normally after that.

**Comment by EarthSalamander42** [comment]
That's some weird interactions xD Never expected that kind of possiblities
