### ISSUE TITLE
X-Heroes 3.43 bugs

### ISSUE THREAD

**Issue by peitschie** [EarthSalamander42/x_hero_siege#2]
Hiya,

Let me know if you prefer one mega issue like this, or one issue per identified bug, as I'm happy to raise them either way 😺 

* [ ] Special events timer for farming event doesn't tick down after completing the first special event (Muradin). It displays 0:00, even though the second event still triggers after the required time
* [x] There are no count-down timers in the spirit beast and other special arenas, even though they timeout after 2mins
* [x] Beast master doesn't appear to have a level 20 upgrade spell? At least, I couldn't identify which had changed, and don't recall seeing it in the upgrade message
* [ ] Beast master + shield of invincibility makes huge spikes come out of the hero! Looks really weird 😆 
* [x] Shield of invincibility is lost if the hero is killed (specifically, was using beast master, and fighting vs all hero images, and died, and the shield vanished from the hero's inventory)
* [ ] Vs Hero Images seems to have a lot more heroes than list time. Not sure if this is a bug... but even on easy, I'm unable to get even close to killing these now 😢 

Thanks again for your hard work. This is a fun mod!

**Comment by peitschie** [comment]
Here;s what the shield looks like:

![20170717131205_1](https://user-images.githubusercontent.com/1052079/28254727-c5da0852-6af2-11e7-8ce8-81e80987b57d.jpg)

**Comment by RodneyMcKay** [comment]
Thanks for reporting! yeah i would like 1 by 1 :) Gonna fix those in 3.43b anyway

**Comment by EarthSalamander42** [comment]
Thanks for reporting! A huge list like that is good, as i can catch the boxes when i fix 1 of them :)

**Comment by EarthSalamander42** [comment]
3.43b Update: 
- Added timers for Arenas
- Shield of Invincibility has been fixed

- for the Special Events Timer bug, couldn't reproduce it
- Beastmaster don't have level 20 ability yet because i've launched 3.43 earlier than expected to fix huge bugs that made the game unplayable, will do later
- Blademail particle: This happens with any hero, when you get teleported somewhere (will fix later, minor bug)
- i didn't understood the last check box, could you re-formulate? :)

**Comment by peitschie** [comment]
> i didn't understood the last check box, could you re-formulate? :)

I'm having a lot of trouble beating the hero images on any level (primarily due to the time limit to be honest, as I'm trying to kill the heroes late game). I haven't checked, but have you increased the number of heroes in that special arena?

**Comment by EarthSalamander42** [comment]
No, the tip is to do this right after Muradin, and not buying tomes before Muradin :)

**Comment by peitschie** [comment]
I've listed across any of the bits from here that aren't fixed in a new 3.43b issue! This one can be closed now if you're done with it 😺

**Comment by peitschie** [comment]
Also, thanks for the tips about the hero images... worked a treat 😀
