### ISSUE TITLE
Archimonde's W skill doesn't work

### ISSUE THREAD

**Issue by peitschie** [EarthSalamander42/x_hero_siege#6]
His W is called "Spiritual Beasts", but doesn't summon anything, or do any damage.

**Comment by EarthSalamander42** [comment]
Well, Archimonde can't be picked atm...

**Comment by peitschie** [comment]
Oh! I got him via Random Hero ☺️ !

**Comment by peitschie** [comment]
Are you able to stop the heroes that aren't yet pickable from being chosen as a random hero? I suspect I've hit a few others like this that are not yet released, but sometimes get given them when choosing random (which I usually do).
