### ISSUE TITLE
Second player in the game appears to have all spells disabled in Duel at end of game

### ISSUE THREAD

**Issue by peitschie** [EarthSalamander42/x_hero_siege#9]
When the final duel is presented at the very end of the game, the other player (i.e., the ones who did not create the game) have all their spells appearing to be disabled. All the spells still appear in the usual place, but are dimmed out as if disabled.

I've seen this with Axe and Space Marine.

**Comment by peitschie** [comment]
So, more research, it seems that the duel only shows what person 1 can see. The other player in my game was playing the blademaster, and found they were invisible to **themselves** whenever they activated windwalk.

**Comment by EarthSalamander42** [comment]
Duel disabled, it was a test feature for the upcoming X Hero Siege Ranked, wich will be there very soon!
